### ISSUE TITLE
strip comments

### ISSUE THREAD

**Issue by az0** [soundcloud/normailize#3]
According to Wikipedia

Comments are allowed with parentheses at either end of the local part; e.g. "john.smith(comment)@example.com" and "(comment)john.smith@example.com" are both equivalent to "john.smith@example.com".

--https://en.wikipedia.org/wiki/Email_address

**Comment by dandv** [comment]
Who implements this obscure spec? Gmail, for one, doesn't:

![image](https://cloud.githubusercontent.com/assets/33569/8765628/a49139ee-2dc9-11e5-8506-b0b288e38de9.png)
