### ISSUE TITLE
Normalize host part

### ISSUE THREAD

**Issue by fulldecent** [soundcloud/normailize#6]
The host part of an email address is case insensitive. Perhaps during normalization the host part can be folded lowercase.

**Comment by fulldecent** [comment]
To be clear, are you still accepting contributions to this project?? If so would a PR that fixes this be in scope to be merged?

**Comment by grobie** [comment]
We do not longer use or maintain this project. Please fork it and consider releasing own versions if you need modifications. I'm going to add a a note to the readme and archive the repo shortly.
